name: "CI"

on:
  push:
    branches:
      - docker-compose

jobs:
  docker-image-build-publish:
    name: Publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Get current version
      #   id: get-version
      #   uses: beaconbrigade/package-json-version@v0.3
      #   with:
      #     path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        run: |
          touch .env
          echo "BASE_URL=${{ secrets.BASE_URL }}" > .env
          cat .env
        shell: bash

      - name: Create .env.local file
        run: |
          touch .env.local
          echo "NEXT_PUBLIC_BASE_URL=${{ secrets.BASE_URL }}" > .env.local
          echo "NEXT_PUBLIC_PORT=${{ secrets.PORT }}" >> .env.local
          echo "NEXT_PUBLIC_API=${{ vars.API }}" >> .env.local
          cat .env.local
          echo ${{ vars.API }}
        shell: bash

      # - name: Log in to the azure container registry
      #   uses: azure/docker-login@v1
      #   with:
      #     registry: registry.azurecr.io
      #     username: ${{ secrets.AZURE_USER }}
      #     password: ${{ secrets.AZURE_PASSWORD }}

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: registry.azurecr.io/blog:latest

      - name: Log in to the github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: { { secrets.GITHUB_TOKEN } }

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          
